import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    utils: 'src/utils.ts',
    'hooks/use-toast': 'src/hooks/use-toast.ts',
    'analytics/index': 'src/lib/analytics/index.ts',
    'india/index': 'src/india/index.ts',
    pdf: 'src/components/ui/data-display/pdf-viewer.tsx',
  },
  format: ['esm', 'cjs'],
  dts: true,
  sourcemap: true,
  clean: false,
  splitting: true,
  injectStyle: false,
  external: [
    'react',
    'react-dom',
    'react/jsx-runtime',
    'date-fns',
    'pdfjs-dist',
    'xlsx',
    'jspdf',
    'jspdf-autotable',
    'react-pdf',
    'recharts',
    'canvas-confetti',
    'embla-carousel-react',
    'cmdk',
    'vaul',
    'react-hook-form',
    'react-day-picker',
    'next-themes',
    'lucide-react',
    'sonner',
    'input-otp',
    'react-resizable-panels',
    'class-variance-authority',
    'clsx',
    'tailwind-merge',
    /^@radix-ui\/.+/,
  ],
});
